# Generated by Django 5.1 on 2026-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_masterschedule_masterdayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/photos/', verbose_name='Фото'),
        ),
    ]
