# Generated by Django 6.0.5 on 2026-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Промокод'),
        ),
    ]
