# Generated by Django 6.0.5 on 2026-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
